"""
Apply per-machine gitignore rules to every git repo found under the
configured search roots.

What this does, per repo:
  1. Determines the current machine (via detect.get_machine()).
  2. Concatenates rule files:
        rules/common.ignore
        rules/machines/<machine>.ignore         (if exists)
        rules/repos/<repo_basename>.ignore      (if exists)
  3. Writes the result to <repo>/.git/info/exclude.
     This is the per-clone exclude file — it is NOT committed and does
     not travel between machines, which is exactly what we want.

Run:
    python apply.py            # apply to all discovered repos
    python apply.py --dry-run  # print what would be written without writing
"""
import sys
from pathlib import Path

from detect import get_machine, find_repos, check_drives, get_hostname


HERE = Path(__file__).resolve().parent
RULES_DIR = HERE / "rules"

# Search roots — edit as you add new machines / checkout locations.
SEARCH_ROOTS = [
    Path(r"D:\Code"),
    Path(r"C:\Users\ohjos\Code"),
    Path(r"F:\Code"),
    Path.home() / "Code",
]

EXCLUDE_HEADER = (
    "# AUTO-GENERATED by ohjoshrules/machine_ignore/apply.py\n"
    "# Machine: {machine}   Hostname: {host}\n"
    "# Edit the rule files under ohjoshrules/machine_ignore/rules/\n"
    "# and re-run apply.py. This file lives in .git/info/exclude and\n"
    "# is NOT committed.\n"
    "\n"
)


def load_rule_file(path: Path) -> str:
    """Return the rule file contents with a header comment, or empty if missing."""
    if not path.exists():
        return ""
    rel = path.relative_to(RULES_DIR)
    body = path.read_text(encoding="utf-8").rstrip()
    if not body:
        return ""
    return f"# --- {rel.as_posix()} ---\n{body}\n\n"


def build_exclude_content(machine: str, repo_name: str) -> str:
    sources = [
        RULES_DIR / "common.ignore",
        RULES_DIR / "machines" / f"{machine}.ignore",
        RULES_DIR / "repos" / f"{repo_name}.ignore",
    ]
    body = "".join(load_rule_file(p) for p in sources)
    return EXCLUDE_HEADER.format(machine=machine, host=get_hostname()) + body


def apply_to_repo(repo_path: Path, machine: str, dry_run: bool = False):
    info_dir = repo_path / ".git" / "info"
    if not info_dir.exists():
        # Could be a worktree or a gitdir pointer — skip.
        return None
    content = build_exclude_content(machine, repo_path.name)
    exclude_path = info_dir / "exclude"
    if dry_run:
        return (exclude_path, content, None)
    # Preserve a backup of any hand-written exclude once, so nothing is lost.
    if exclude_path.exists():
        backup = info_dir / "exclude.bak_before_machine_ignore"
        if not backup.exists():
            backup.write_text(
                exclude_path.read_text(encoding="utf-8"), encoding="utf-8"
            )
    exclude_path.write_text(content, encoding="utf-8")
    return (exclude_path, content, True)


def main(argv):
    dry_run = "--dry-run" in argv

    machine = get_machine()
    host = get_hostname()
    print(f"Hostname: {host}")
    print(f"Machine:  {machine}")
    print()

    check_drives()
    print()

    repos = find_repos(SEARCH_ROOTS)
    print(f"Found {len(repos)} git repos under:")
    for r in SEARCH_ROOTS:
        marker = "(exists)" if r.exists() else "(missing)"
        print(f"  {r}  {marker}")
    print()

    applied = []
    skipped = []
    for repo in repos:
        result = apply_to_repo(repo, machine, dry_run=dry_run)
        if result is None:
            skipped.append(repo)
            continue
        exclude_path, content, wrote = result
        status = "DRY-RUN" if dry_run else "wrote"
        print(f"  {status}: {exclude_path}  ({len(content.splitlines())} lines)")
        applied.append(repo)

    print()
    print(f"Applied to {len(applied)} repos, skipped {len(skipped)}.")
    if skipped:
        for s in skipped:
            print(f"  skipped: {s}")

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
